# Generated by Django 3.2.5 on 2022-11-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('create_time', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('head', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GovUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('belong_to', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'gov_url',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PolicyUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_url', models.TextField(blank=True, null=True)),
                ('policy_title', models.TextField(blank=True, null=True)),
                ('belong_to', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('create_time', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policy_url',
                'managed': True,
            },
        ),
    ]
