# Generated by Django 3.2.5 on 2022-11-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221118_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=45)),
                ('portrait', models.ImageField(blank=True, upload_to='portrait/%Y%m%d/')),
            ],
            options={
                'db_table': 'user_info_data',
                'managed': True,
            },
        ),
    ]
