# Generated by Django 3.2.5 on 2022-11-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='last_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
