# Generated by Django 3.2.5 on 2022-11-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_follow_last_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follow_category',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
