# Generated by Django 3.2.5 on 2022-11-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221124_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info_data',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='portrait'),
        ),
    ]
