# Generated by Django 3.2.5 on 2022-11-27 06:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_info_data_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info_data',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
