# Generated by Django 3.2.5 on 2022-11-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_info_data_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyurl',
            old_name='city',
            new_name='city',
        ),
    ]
